### PR TITLE
fix(checkbox): add aria attributes to ignore checkbox icon

### LINKED ISSUE #30231: bug: ion-checkbox svg visible to assistive technology
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

`ion-checkbox` has an svg checkbox icon that currently appears in the accessibility tree as having role 'image', and can be targeted by screen readers, but with no other contextual information about the svgs, making it difficult to understand.

Using VoiceOver, I get the following experience when stepping into a checkbox and past the label: 
> Image

Scanning the page with analysis tools such as axe devTools will also result in "SVG element missing accessible name" types of errors.

### Expected Behavior

I think the svg should be hidden from AT with `aria-hidden="true"` or similar, so only the entire checkbox control and any label inside is reachable. 

### Steps to Reproduce

1. Navigate to a page with an `ion-checkbox`, e.g. https://stackblitz.com/edit/r1exi21m
2. Browse the page with a screen-reader, and step into the checkbox control.
3. See that svg inside ion-checkbox is reachable

### Code Reproduction URL

https://stackblitz.com/edit/r1exi21m

### Ionic Info

Reproduced in stackblitz.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ShaneK**
Issue number: resolves #30231

---------

## What is the current behavior?

Currently, if you're using voiceover on Chrome or Firefox, you can navigate the checkbox in such a way that it announces the checkbox image, which provides no context to what you're actually selecting.

## What is the new behavior?

With this change, you can no longer select the checkbox image.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

[Screen](https://ionic-framework-git-ionic-56-ionic1.vercel.app/src/components/checkbox/test/basic)

### CODE REVIEW

File: core/src/components/checkbox/checkbox.tsx [hunk 1]
```diff
@@ -328,7 +328,7 @@ export class Checkbox implements ComponentInterface {
             {this.renderHintText()}
           </div>
           <div class="native-wrapper">
-            <svg class="checkbox-icon" viewBox="0 0 24 24" part="container">
+            <svg class="checkbox-icon" viewBox="0 0 24 24" part="container" aria-hidden="true" role="presentation">
```
Comment (brandyscarney) [inline core/src/components/checkbox/checkbox.tsx]:
```suggestion
            <svg class="checkbox-icon" viewBox="0 0 24 24" part="container" aria-hidden="true">
```

We shouldn't need `role` since it is removed from the accessibility tree by using `aria-hidden`

**Review by brandyscarney — CHANGES_REQUESTED** [review]

File: core/src/components/checkbox/checkbox.tsx (hunk 1 above)
Comment (ShaneK) [reply core/src/components/checkbox/checkbox.tsx]: Good catch! Accidentally left it around from initial testing 😅
